#!/bin/bash

cat << EOF
Alexei Starovoitov <ast@kernel.org>
Daniel Borkmann <daniel@iogearbox.net>
Martin KaFai Lau <kafai@fb.com>
Song Liu <songliubraving@fb.com>
Paul Turner <pjt@google.com>
Jann Horn <jannh@google.com>
Hao Luo <haoluo@google.com>
EOF


